# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170110_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 3, 3, 33, 414098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 3, 3, 33, 414623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 3, 3, 33, 415077, tzinfo=utc)),
        ),
    ]
