# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 03:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20170114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageskin',
            name='docfile',
            field=models.FileField(default=None, upload_to='unknown/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 3, 38, 45, 451598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 3, 38, 45, 452110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 3, 38, 45, 452674, tzinfo=utc)),
        ),
    ]
