# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20170116_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourcedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 27, 45, 774014, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 27, 45, 774463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 27, 45, 774880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 27, 45, 775428, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='imageskin',
            name='sourcedata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Sourcedata'),
        ),
    ]
