# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20170117_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedata',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 30, 26, 755772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 30, 26, 756192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 30, 26, 756691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 5, 30, 26, 755263, tzinfo=utc)),
        ),
    ]
