# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20170117_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 5, 41, 14, 309717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 5, 41, 14, 310136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='unknown'),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 5, 41, 14, 310636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 5, 41, 14, 309372, tzinfo=utc)),
        ),
    ]
