# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20170119_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 6, 1, 219038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 6, 1, 219464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='dataset'),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 6, 1, 219963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 6, 1, 218672, tzinfo=utc)),
        ),
    ]
