# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20170119_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.AddField(
            model_name='disease',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 10, 48, 344771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 10, 48, 345188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 10, 48, 345729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 6, 10, 48, 344412, tzinfo=utc)),
        ),
    ]
