# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0014_auto_20170119_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('state', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 1, 22, 1, 53, 22, 54191, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 1, 53, 22, 52766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 1, 53, 22, 53182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 1, 53, 22, 53684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 22, 1, 53, 22, 52418, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='imageskin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Imageskin'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
