# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20170302_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 176073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 177498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 177960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 176493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 176990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 0, 44, 28, 175716, tzinfo=utc)),
        ),
    ]
