# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_auto_20170302_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 324461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 325901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 326446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 324887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 325390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 1, 4, 55, 324111, tzinfo=utc)),
        ),
    ]
