# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_auto_20170302_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 512291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 514173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 514754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 512850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imageskin',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 513513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 4, 17, 9, 39, 511598, tzinfo=utc)),
        ),
    ]
