# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0022_auto_20170319_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=200)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('imageskin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Imageskin')),
            ],
        ),
    ]
