# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropimage',
            name='originalHeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cropimage',
            name='originalWidth',
            field=models.IntegerField(default=0),
        ),
    ]
