# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20170321_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropimage',
            name='transform',
            field=models.CharField(default='', max_length=200),
        ),
    ]
